services:
  app:
    build: .
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - PORT=${PORT}
      - SECRET_KEY=${SECRET_KEY}
    ports:
      - 3000:3000
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: bitnami/postgresql:latest
    restart: always
    ports:
      - 5432:5432
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'pg_isready -h 127.0.0.1 -U ${POSTGRES_USER} -d ${POSTGRES_DB}',
        ]
      interval: 5s
      timeout: 10s
      retries: 5
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - expenses_db:/bitnami/postgresql

volumes:
  expenses_db:
