@token = {{login.response.body.token}}
@id = "679c06bb-81bb-4857-8438-9ee9643a13b1"

POST http://localhost:3000/auth/signup
content-type: application/json

{
    "name": "John Doe",
    "email": "johndoe@gmail.com",
    "password": "12345678"
}

###

# @name login
POST http://localhost:3000/auth/login
content-type: application/json

{
    "email": "johndoe@gmail.com",
    "password": "12345678"
}

###

POST http://localhost:3000/expenses
content-type: application/json
Authorization: {{token}}

{
    "description": "Zomboid",
    "category": "electronics",
    "amount": 37.99,
    "date": "2024-09-02T19:54:23.587Z"
}

###

DELETE http://localhost:3000/expenses/679c06bb-81bb-4857-8438-9ee9643a13b1
content-type: application/json
Authorization: {{token}}

###

GET http://localhost:3000/expenses
content-type: application/json
Authorization: {{token}}