@token = {{login.response.body.token}}

POST http://localhost:3000/auth/signup
content-type: application/json

{
    "name": "John Doe",
    "email": "johndoe@gmail.com",
    "password": "12345678"
}

###

# @name login
POST http://localhost:3000/auth/login
content-type: application/json

{
    "email": "johndoe@gmail.com",
    "password": "12345678"
}

###

POST http://localhost:3000/expenses
content-type: application/json
Authorization: {{token}}

{
    "description": "Factorio",
    "category": "electronics",
    "amount": 5.99,
    "date": "2024-08-01T10:54:23.587Z"
}

###

@id = 679c06bb-81bb-4857-8438-9ee9643a13b1
DELETE http://localhost:3000/expenses/{{id}}
content-type: application/json
Authorization: {{token}}

###

GET http://localhost:3000/expenses
content-type: application/json
Authorization: {{token}}

###

# pastWeek, pastMonth, past3Months

GET http://localhost:3000/expenses?filter=pastWeek
content-type: application/json
Authorization: {{token}}

###

# YYYY-MM-DD

GET http://localhost:3000/expenses?startAt=2024-08-01&endAt=2024-09-02
content-type: application/json
Authorization: {{token}}